[package]
name = "guessing_game"
version = "0.2.0"
authors = ["Bajramovic Dino <dbajramo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"